<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="BYTE_UNION" Id="{25455c5f-befe-4f02-84c5-95e1161be66a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BYTE_UNION

VAR_INPUT
	Upper_Byte:			BYTE;
	Lower_Byte:			BYTE;
END_VAR

VAR_OUTPUT
	United_Word:		WORD;
END_VAR

VAR
	Aux_Word:			WORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Aux_Word:= BYTE_TO_WORD (Upper_Byte);
United_Word:= SHL (Aux_Word, 8) + Lower_Byte;
]]></ST>
    </Implementation>
    <LineIds Name="BYTE_UNION">
      <LineId Id="10" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>