<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Analyzers" Id="{907aa627-47e3-4482-a979-79b393bfe7d2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Analyzers
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Analyzers">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>