<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_EL3453_handling" Id="{607e69df-f40a-48cc-8fb1-54e07d0aad99}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_EL3453_handling
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_EL3453_handling">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>