<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU" Id="{39f4c466-d879-41dc-93cf-eafefe0349dd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>